loog/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginPage.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/<str:uidb64_invite_id>/<str:token>/", views.RegisterView.as_view(), name='register'),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/set-inviter-tags/", views.SetInviterTagView.as_view(), name="set_tags"),
    path("profile/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("invite/", views.InvitePage.as_view(), name="invite"),
    path("google/login/", views.google_login, name="google_login"),
    path("google/register/", views.google_register, name="google_register"),
    path("google/auth/", views.google_authorize, name="google_authorize"),
]

loog/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"


urlpatterns = [
    path("history/", views.ChatSessionList.as_view(), name="history"),
    path("<str:room_name>/", views.ChatSessionView.as_view(), name="session"),
    path("<str:room_name>/tag/", views.session_post_tag, name="session-tag"),
    path("join/<str:room_name>/", views.join_chat_session, name="join-session")
]

loog/loog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),
    path("api/notifications/", include("notifications.api.routers")),
    path("discovery/", include("discovery.urls", namespace="discovery")),
    path("api/discovery/", include("discovery.api.routers")),
    path("chat/", include(("chat.urls", "chat"), namespace="chat")),
    path("api/chat/", include("chat.api.routers")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("api/accounts/", include("accounts.api.routers")),
    path("", include("main.urls", namespace="main")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loog/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from discovery.forms import TagForm
from .models import Profile, InvitedUser, User

User = get_user_model()


class RegisterForm(UserCreationForm, TagForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['comma_separated_tags'].label = 'Inviter Tags'

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError(_("This email already exists."))
        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', ]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["avatar", "location", "birthdate", "preferences"]


class InviteForm(forms.ModelForm, TagForm):
    email = forms.EmailField(
        help_text=_("Your invitation link will valid for next 24 hours.")
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_exists = User.objects.filter(email=email).exists()

        if user_exists:
            raise ValidationError(_("This email has an account!"), code='invalid')

        return email

    class Meta:
        model = InvitedUser
        fields = ["email", "comma_separated_tags"]

loog/accounts/api/views.py
from rest_framework import viewsets, permissions
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.models import Profile, User, InvitedUser
from .serializers import ProfileSerializer, UserSerializer, InvitedUserSerializer, WaitListSerializer


class UsersViewSet(viewsets.ModelViewSet):
    """CRUD API of User for admin users"""
    serializer_class = UserSerializer
    queryset = User.objects.all()
    permissions = (permissions.IsAdminUser,)


class ProfilesViewSet(viewsets.ModelViewSet):
    """CRUD API of Profile for admin users"""
    serializer_class = ProfileSerializer
    queryset = Profile.objects.all()
    permission_classes = (permissions.IsAdminUser,)


class InvitedUsersViewSet(viewsets.ModelViewSet):
    """CRUD API of InvitedUser for admin users"""
    serializer_class = InvitedUserSerializer
    queryset = InvitedUser.objects.all()
    permissions = (permissions.IsAdminUser,)


class WaitListAPI(APIView):
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get(self, request, *args, **kwargs):
        serializer = WaitListSerializer(data=request.GET)
        serializer.is_valid(raise_exception=True)

        admin_user = User.objects.filter(is_superuser=True).first()
        email = serializer.data.get('email')
        already_invited = InvitedUser.objects.filter(email=email).exists()
        if already_invited:
            return Response(data={"error": "Already invited!"}, status=400)

        obj = InvitedUser.objects.create(
            inviter=admin_user,
            email=email,
            comma_separated_tags='new user, wait list,'
        )
        obj.send_invitation_email(
            host_name=request.build_absolute_uri("/")[:-1]
        )
        return Response(data=serializer.data)

loog/accounts/views.py
from authlib.integrations.django_client import OAuth
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic

from core.mixins import ProfileRequiredMixin

from discovery.forms import TagForm
from discovery.models import TagAssignment
from discovery.selectors import get_tag_count, get_tag_by_name

from .forms import RegisterForm, ProfileForm, InviteForm
from .models import User
from .selectors import get_invites_count, get_inviter, get_invite_obj_from_url, get_invite_obj_from_inviter_username
from .services import register_user_with_tags
from .tokens import registration_token

CONF_URL = 'https://accounts.google.com/.well-known/openid-configuration'
oauth = OAuth()
oauth.register(
    name='google',
    server_metadata_url=CONF_URL,
    client_kwargs={
        'scope': 'openid email profile'
    }
)

messages.ERROR = 'danger'


def google_login(request):
    """
    Builds a full authorize callback uri and sets auth_method to login.
    """
    redirect_uri = request.build_absolute_uri(
        reverse('accounts:google_authorize')
    )
    request.session['auth_method'] = 'login'
    return oauth.google.authorize_redirect(request, redirect_uri)


def google_register(request):
    """
    Builds a full authorize callback uri and sets auth_method to register.
    """
    redirect_uri = request.build_absolute_uri(
        reverse_lazy('accounts:google_authorize')
    )
    request.session['auth_method'] = 'register'
    request.session['invited_email'] = request.GET.get('email', '')
    request.session['inviter'] = request.GET.get('inviter', '')
    return oauth.google.authorize_redirect(request, redirect_uri)


def google_authorize(request):
    token = oauth.google.authorize_access_token(request)
    userinfo = oauth.google.parse_id_token(request, token)
    email = userinfo.get("email")
    auth_method = request.session.pop('auth_method')

    if email is None:
        messages.error(request, _("Google auth failed."))
        return redirect('accounts:login')

    users = User.objects.filter(email=email)
    users_count = users.count()

    if auth_method == 'login':
        if users_count == 1:
            login(request, users[0])
        elif users_count == 0:
            messages.error(request, _("You don't have account in Loog!"))
            return redirect('accounts:login')
        else:
            messages.error(request, _("Server Error 500, Call site admins!"))
            return redirect('accounts:login')
    elif auth_method == 'register':
        if users_count > 0:
            messages.error(request, _("Account already exists, try to login with google!"))
            return redirect('accounts:login')
        else:
            invited_email = request.session.pop('invited_email')
            inviter = request.session.pop('inviter')
            if invited_email != email:
                messages.error(request,
                               _("Can not register with this email address, use password or related social media."))
                return redirect('main:homepage')

            invite_obj = get_invite_obj_from_inviter_username(inviter, email)
            if invite_obj is None:
                messages.error(request,
                               _("Sorry, you didn't invite to Loog, if you received an email please call admins."))
                return redirect('main:homepage')

            user = User.objects.create(
                username=email.split('@')[0],
                email=email,
                first_name=userinfo.get('given_name'),
                last_name=userinfo.get('family_name')
            )
            register_user_with_tags(
                new_user=user,
                invite_obj=invite_obj
            )
            login(request, user)

    return redirect('main:homepage')


class LoginPage(auth_views.LoginView):
    """
    Session-based login.
    Note: It will redirect to homepage after a successful login.
    You can change this in settings --> LOGIN_REDIRECT_URL
    """
    template_name = "accounts/login.html"


class LogoutView(auth_views.LogoutView):
    """
    Session-based logout.
    Note: It will redirect to login page after a successful logout.
    You can change this in settings --> LOGOUT_REDIRECT_URL
    """
    pass


class RegisterView(generic.View):
    # TODO: a cleaner one?
    def get(self, request, uidb64_invite_id, token):
        invite_obj = get_invite_obj_from_url(uidb64_invite_id)
        if invite_obj is not None and registration_token.check_token(invite_obj.inviter, token):
            form = RegisterForm(
                initial={'email': invite_obj.email},
            )
            return render(request, 'accounts/register.html', context={'form': form, 'inviter': invite_obj.inviter})
        else:
            return HttpResponseForbidden("Sorry! You don't have access to this link...")

    def post(self, request, uidb64_invite_id, token):
        invite_obj = get_invite_obj_from_url(uidb64_invite_id)
        if invite_obj is not None and registration_token.check_token(invite_obj.inviter, token):
            form = RegisterForm(request.POST)
            if form.is_valid():
                new_user = form.save(commit=True)
                register_user_with_tags(
                    new_user=new_user,
                    invite_obj=invite_obj,
                    new_user_tags=form.cleaned_data.get("comma_separated_tags")
                )
                messages.success(request, "Registered successfully.")
                return redirect("accounts:login")
            else:
                return render(request, 'accounts/register.html', context={'form': form, 'inviter': invite_obj.inviter})
        return HttpResponseForbidden(_("Sorry! You don't have access to this link..."))


class ProfileView(ProfileRequiredMixin, generic.TemplateView):
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        user = self.request.user
        profile = user.profile
        tags = {"gived": get_tag_count(giver=user), "recieved": get_tag_count(receiver=user)}
        context["tags"] = tags
        context["profile"] = profile
        return context


class ProfileUpdateView(SuccessMessageMixin, LoginRequiredMixin, generic.FormView):
    template_name = "accounts/profile_update.html"
    form_class = ProfileForm
    success_url = reverse_lazy("accounts:profile")
    success_message = _("You profile successfully updated.")

    def get_form(self, form_class=ProfileForm):
        profile = self.request.user.profile
        return form_class(instance=profile, **self.get_form_kwargs())

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(ProfileUpdateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        tag_exists = TagAssignment.objects.filter(giver=self.request.user).exists()
        if not tag_exists:
            context['tag_form'] = TagForm()
        return context


class SetInviterTagView(LoginRequiredMixin, generic.View):
    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        profile = request.user.profile
        tag_form = TagForm(request.POST)
        profile_form = ProfileForm(instance=profile)
        context = {
            'form': profile_form
        }
        if tag_form.is_valid():
            for tag in tag_form.cleaned_data['comma_separated_tags'].split(","):
                TagAssignment.objects.create(
                    tag=get_tag_by_name(tag),
                    receiver=get_inviter(self.request.user.email),
                    giver=self.request.user
                )
            return redirect("accounts:profile")
        else:
            context.update({'tag_form': tag_form})

        return render(request, 'accounts/profile_update.html', context)


class InvitePage(SuccessMessageMixin, ProfileRequiredMixin, generic.CreateView):
    template_name = 'accounts/invite.html'
    form_class = InviteForm
    success_url = reverse_lazy("accounts:invite")
    success_message = _("You friend successfully invited. We will send him/her an invitation email.")

    def form_valid(self, form):
        invited = form.save(commit=False)
        if get_invites_count(self.request.user) <= 4:
            invited.inviter = self.request.user
            invited.save()
            invited.send_invitation_email(host_name=self.request.build_absolute_uri("/")[:-1])
        else:
            messages.error(self.request, message=_("You cannot invite more than 5 friends."))
            return redirect("accounts:invite")
        return super(InvitePage, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(InvitePage, self).get_context_data(**kwargs)
        context['current_invites'] = get_invites_count(self.request.user)
        return context

loog/templates/accounts/invite.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Invite your friends
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
{% endblock %}

{% block content %}


<div class="container mx-auto">
    <div class="alert alert-info mt-3" role="alert">
        <p class="font-weight-light mt-3" data-toggle="tooltip"></p>
        <p class="lead" data-toggle="tooltip" data-placement="top">
            If your friend does not have an account, invite him or her with at least 5 tags!
        </p>
        <p>
            You invited {{ current_invites }} / 5 of your invites!
        </p>
    </div>

    <div class="row">
        <div class="col-12 pb-4">
            <div class="card p-4">
                <form action="." method="POST">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
        <div class="col-sm-12 col-md-12 col-lg-9 pb-4">
        </div>
    </div>
</div>


{% endblock %}

{% block js %}
    <script src="{% static 'js/tagsinput.js' %}"></script>
{% endblock %}

loog/templates/accounts/login.html
{% extends "base_light.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Login {% endblock %} 

{% block content %}

<!-- Main content -->
<div class="main-content">
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
        <div class="container">
            <div class="header-body text-center mb-7">
                <div class="row justify-content-center">
                    <div class="col-xl-5 col-lg-6 col-md-8 px-5">
                        <h1 class="text-white">Welcome!</h1>
                        <p class="text-lead text-white">
                            Some text here...
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
        </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary border-0 mb-0">
                    <!-- Social Accounts -->
                    <div class="card-header bg-transparent pb-5">
                        <div class="text-muted text-center mt-2 mb-3"><small>Sign in with</small></div>
                        <div class="btn-wrapper text-center">
                            <a href="{% url 'accounts:google_login' %}" class="btn btn-neutral btn-icon">
                                <span class="btn-inner--icon"><img src="{% static 'img/icons/common/google.svg' %}" alt="google-logo"></span>
                                <span class="btn-inner--text">Google</span>
                            </a>
                        </div>
                    </div>
                    <div class="card-body px-lg-5 py-lg-5">
                        <div class="text-center text-muted mb-4">
                            <small>Sign in with credentials</small>
                        </div>
                        <form role="form" method="POST">
                            {% csrf_token %}
                            {{ form | crispy }}
                            
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary my-4">Sign in</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {% comment %} <a href="#" class="text-light"><small>Forgot password?</small></a> {% endcomment %}
                    </div>
                    <div class="col-6 text-right">
                        {% comment %} <a href="#" class="text-light"><small>Create new account</small></a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer_mini.html' %}

{% endblock %}

loog/templates/accounts/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}


    <div class="container">
        <div class="row">
            <!-- Profile Card -->
            <div class="col-xl-4 mt-5">
                <div class="card card-profile">
                    <img src="{% static 'img/theme/img-1-1000x600.jpg' %}" alt="Image placeholder" class="card-img-top">
                    <div class="row justify-content-center">
                        <div class="col-lg-3 order-lg-2">
                            <div class="card-profile-image">
                                <a href="{% url 'accounts:profile' %}">
                                    <img src="{{ profile.get_avatar }}" alt="profile-photo" class="rounded-circle">
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'accounts:invite' %}" class="btn btn-sm btn-info  mr-4 ">
                                <span class="fa fa-mail-forward"></span>
                                Invite
                            </a>
                            <a href="{% url 'accounts:profile_update' %}" class="btn btn-sm btn-warning float-right">
                                <span class="fa fa-pencil"></span>
                                Edit
                            </a>
                        </div>
                    </div>
                    <div class="card-body pt-0">
                        {% comment %}
                        <div class="row">
                            <div class="col">
                                <div class="card-profile-stats d-flex justify-content-center">
                                    <div>
                                        <span class="heading">22</span>
                                        <span class="description">Friends</span>
                                    </div>
                                    <div>
                                        <span class="heading">10</span>
                                        <span class="description">Photos</span>
                                    </div>
                                    <div>
                                        <span class="heading">89</span>
                                        <span class="description">Comments</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endcomment %}
                        <div class="text-center">
                            <h5 class="h3">
                                {{ profile.get_name_or_username }}<span
                                    class="font-weight-light">, {{ profile.age }}</span>
                            </h5>
                            <div class="h5 font-weight-300">
                                <i class="ni location_pin mr-2"></i>{{ profile.location }}
                            </div>
                            <div class="h5 mt-4">
                                <i class="ni business_briefcase-24 mr-2"></i>{{ profile.user.email }}
                            </div>
                            <div>
                                <i class="ni education_hat mr-2"></i>Preferences: {{ profile.get_preferences }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Tags -->
            <div class="col-xl-8 ">
                <div class="row">
                    {% for key, value in tags.items %}
                    <div class="col-sm">
                        <p class="text-uppercase mt-3 text-center">{{ key }}</p>
                        <ul class="list-group">
                            {% for tag, count in value.items %}
                                <a href="#"
                                   class="list-group-item d-flex justify-content-between align-items-center">{{ tag }}

                                    {% if count >= 5 %}
                                        <span class="badge badge-danger badge-pill">{{ count }}</span>
                                    {% elif count >= 2 %}
                                        <span class="badge badge-warning badge-pill">{{ count }}</span>
                                    {% else %}
                                        <span class="badge badge-primary badge-pill">{{ count }}</span>
                                    {% endif %}

                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>



{% endblock %}

loog/templates/accounts/profile_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Profile {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        {% if tag_form %}
            <h1>
                Tag your inviter...
            </h1>
            <form action="{% url 'accounts:set_tags' %}" method="post">
                {% csrf_token %}
                {{ tag_form | crispy }}
                <button class="btn btn-primary" type="submit">Submit</button>

            </form>
        {% endif %}
        <h1 class="mt-5">Profile</h1>
        <form action="{% url 'accounts:profile_update' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>

    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/tagsinput.js' %}"></script>
{% endblock %}

loog/templates/accounts/register.html
{% extends "base_light.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Register {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
{% endblock %}

{% block content %}

<!-- Main content -->
<div class="main-content">
    <!-- Header -->
    <div class="header bg-gradient-primary py-7 py-lg-8 pt-lg-9">
        <div class="container">
            <div class="header-body text-center mb-7">
                <div class="row justify-content-center">
                    <div class="col-xl-5 col-lg-6 col-md-8 px-5">
                        <h1 class="text-white">Congradulations!</h1>
                        <p class="text-lead text-white">
                            You have been invited by {{ inviter }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="separator separator-bottom separator-skew zindex-100">
            <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
          <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
        </svg>
        </div>
    </div>
    <!-- Page content -->
    <div class="container mt--8 pb-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary border-0 mb-0">
                    <div class="card-header bg-transparent pb-5">
                        <div class="text-muted text-center mt-2 mb-3"><small>Signup with</small></div>
                        <div class="btn-wrapper text-center">
                            <a href="{% url 'accounts:google_register' %}?email={{ form.initial.email }}&inviter={{ inviter }}" class="btn btn-neutral btn-icon">
                                <span class="btn-inner--icon"><img src="{% static 'img/icons/common/google.svg' %}" alt="google-logo"></span>
                                <span class="btn-inner--text">Google</span>
                            </a>
                        </div>
                    </div>
                    <div class="card-body px-lg-5 py-lg-5">
                        <div class="text-center text-muted mb-4">
                            <small>It's time to join!</small>
                        </div>
                        <form role="form" method="POST">
                            {% csrf_token %}
                            {{ form | crispy }}
                            
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary my-4">Signup</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        {% comment %} <a href="#" class="text-light"><small>Forgot password?</small></a> {% endcomment %}
                    </div>
                    <div class="col-6 text-right">
                        {% comment %} <a href="#" class="text-light"><small>Create new account</small></a> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer_mini.html' %}

{% endblock %}

{% block js %}
    <script src="{% static 'js/tagsinput.js' %}"></script>
{% endblock %}