loog/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginPage.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/<str:uidb64_invite_id>/<str:token>/", views.RegisterView.as_view(), name='register'),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/set-inviter-tags/", views.SetInviterTagView.as_view(), name="set_tags"),
    path("profile/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("invite/", views.InvitePage.as_view(), name="invite"),
    path("google/login/", views.google_login, name="google_login"),
    path("google/register/", views.google_register, name="google_register"),
    path("google/auth/", views.google_authorize, name="google_authorize"),
]

loog/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"


urlpatterns = [
    path("history/", views.ChatSessionList.as_view(), name="history"),
    path("<str:room_name>/", views.ChatSessionView.as_view(), name="session"),
    path("<str:room_name>/tag/", views.session_post_tag, name="session-tag"),
    path("join/<str:room_name>/", views.join_chat_session, name="join-session")
]

loog/loog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),
    path("api/notifications/", include("notifications.api.routers")),
    path("discovery/", include("discovery.urls", namespace="discovery")),
    path("api/discovery/", include("discovery.api.routers")),
    path("chat/", include(("chat.urls", "chat"), namespace="chat")),
    path("api/chat/", include("chat.api.routers")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("api/accounts/", include("accounts.api.routers")),
    path("", include("main.urls", namespace="main")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loog/main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.HomePage.as_view(), name="homepage"),
    path("about/", views.AboutPage.as_view(), name="about_page"),
]

loog/templates/base.html
{% load static %}

<!doctype html>
<html lang="{{ LANGUAGE_CODE|default:" en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Discovery/Chat Application">
    <meta name="vapid-key"
        content="BItDtGwdGRnST9VhBeMR5ZnSbCej3hxwVBUyr5f5AF-lHQU6hr1s7d_1lHbLGBUKqoXasEqbIYgeqOuKOC9SCF4">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">

    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'css/argon.css' %}" type="text/css">

    <!-- Global Base CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />


    {% block css %}

    {% endblock %}

    <title>{% block title %}LOOG{% endblock %}</title>
</head>

<body>

    <div class="main-content" id="panel">
        {% include 'header.html' %}

        {% if messages %}
        {% include 'messages.html' with messages=messages %}
        {% endif %}

        <div class="container-fluid">
            {% block content %}{% endblock %}
            {% include 'footer.html' %}
        </div>
    </div>


    <!-- Core -->
    <script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'vendor/jquery-scroll-lock/jquery-scrollLock.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" async=""></script>

    <!-- Argon JS -->
    <script src="{% static 'js/argon.js' %}"></script>

    <!-- Firebase JS -->
    <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase.js"></script>

    <!-- Global Base JS -->
    <script src="{% static 'js/base.js' %}"></script>

    {% block js %}

    {% endblock %}
</body>

</html>

loog/templates/base_light.html
{% load static %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE|default:" en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Discovery/Chat Application">

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">

    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'css/argon.css' %}" type="text/css">

    <!-- Global Base CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>


    {% block css %}

    {% endblock %}

    <title>{% block title %}Loog{% endblock %}</title>
</head>

<body class="bg-default">

{% if messages %}
    {% include 'messages.html' with messages=messages %}
{% endif %}

{% block content %}{% endblock %}


<!-- Core -->
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/js-cookie/js.cookie.js' %}"></script>
<script src="{% static 'vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'vendor/jquery-scroll-lock/jquery-scrollLock.min.js' %}"></script>

<!-- Argon JS -->
<script src="{% static 'js/argon.js' %}"></script>

<!-- Firebase JS -->
<script src="https://www.gstatic.com/firebasejs/9.2.0/firebase.js"></script>

<!-- Global Base JS -->
<script src="{% static 'js/base.js' %}"></script>

{% block js %}

{% endblock %}
</body>

</html>

loog/templates/footer.html
<!-- Footer -->
<footer class="footer footer-dark position-fixed fixed-bottom mx-4 pt-0">
    <div class="row align-items-center justify-content-lg-between">
        {% include 'footer_base.html' %}
    </div>
</footer>

loog/templates/footer_base.html
<div class="col-lg-6">
    <div class="copyright text-center  text-lg-left  text-muted">
        &copy; <script type="text/javascript">document.write("" + new Date().getFullYear());</script>
        <a href="{% url 'main:homepage' %}" class="font-weight-bold ml-1" target="_blank">Loog</a>
    </div>
</div>
<div class="col-lg-6">
    <ul class="nav nav-footer justify-content-center justify-content-lg-end">
        <li class="nav-item">
            <a onclick="wait_list_click();" class="nav-link" target="_blank">Wait List</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'main:about_page' %}" class="nav-link" target="_blank">About</a>
        </li>
    </ul>
</div>

loog/templates/footer_mini.html
<!-- Footer -->
<footer class="py-5" id="footer-main">
    <div class="container">
        <div class="row align-items-center justify-content-lg-between">
            {% include 'footer_base.html' %}
        </div>
    </div>
</footer>

loog/templates/header.html
{% load static %}
<!-- Topnav -->
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Logo -->
            <a href="{% url 'main:homepage' %}" class="mr-2">
                <h1 class="text-white">LOOG</h1>
            </a>

            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                        data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <i class="ni ni-bell-55"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
                        <!-- Dropdown header -->
                        <div class="px-3 py-3">
                            <h6 class="text-sm text-muted m-0">You have <strong class="text-primary"
                                    id="notificationCount">0</strong>
                                notifications.</h6>
                        </div>
                        <!-- List group -->
                        <div class="list-group list-group-flush" id="notificationList">

                        </div>
                        {% comment %}
                        <!-- View all -->
                        <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View
                            all</a>
                        {% endcomment %}
                    </div>
                </li>
                {% comment %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <i class="ni ni-ungroup"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
                        <div class="row shortcuts px-4">
                            <a href="#!" class="col-4 shortcut-item">
                                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                                    <i class="ni ni-calendar-grid-58"></i>
                                </span>
                                <small>Calendar</small>
                            </a>
                            <a href="#!" class="col-4 shortcut-item">
                                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                                    <i class="ni ni-email-83"></i>
                                </span>
                                <small>Email</small>
                            </a>
                            <a href="#!" class="col-4 shortcut-item">
                                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                                    <i class="ni ni-credit-card"></i>
                                </span>
                                <small>Payments</small>
                            </a>
                            <a href="#!" class="col-4 shortcut-item">
                                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                                    <i class="ni ni-books"></i>
                                </span>
                                <small>Reports</small>
                            </a>
                            <a href="#!" class="col-4 shortcut-item">
                                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                                    <i class="ni ni-pin-3"></i>
                                </span>
                                <small>Maps</small>
                            </a>
                            <a href="#!" class="col-4 shortcut-item">
                                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                                    <i class="ni ni-basket"></i>
                                </span>
                                <small>Shop</small>
                            </a>
                        </div>
                    </div>
                </li>
                {% endcomment %}
                {% else %}
                <a class="nav-link pr-0" href="{% url 'accounts:login' %}" role="button">
                    <div class="media align-items-center">
                        <span class="fa fa-user-circle-o"></span>
                        <div class="media-body  ml-2  d-none d-lg-block">
                            <span class="mb-0 text-sm  font-weight-bold">Login</span>
                        </div>
                    </div>
                </a>
                {% endif %}

            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                <img alt="User Avatar" src="{{ user.profile.get_avatar }}">
                            </span>
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">
                                    {% if user.get_full_name %}
                                    {{ user.get_full_name }}{% else %} {{ user.username }}
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <a href="{% url 'accounts:profile' %}" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>My profile</span>
                        </a>
                        <a href="{% url 'accounts:invite' %}" class="dropdown-item">
                            <i class="fa fa-mail-forward"></i>
                            <span>Invite Friends</span>
                        </a>
                        <a href="{% url 'chat:history' %}" class="dropdown-item">
                            <i class="fa fa-comment"></i>
                            <span>Chat History</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'accounts:logout' %}" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </li>
            </ul>
            {% endif %}

        </div>
    </div>
</nav>

loog/templates/messages.html
<div class="container">
    {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% else %}default{% endif %} alert-dismissible fade show mt-3" role="alert">
            <span class="alert-icon"><i class="ni ni-notification-70"></i></span>
            <span class="alert-text">
                {{ message }}
            </span>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
</div>