loog/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginPage.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("register/<str:uidb64_invite_id>/<str:token>/", views.RegisterView.as_view(), name='register'),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/set-inviter-tags/", views.SetInviterTagView.as_view(), name="set_tags"),
    path("profile/update/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("invite/", views.InvitePage.as_view(), name="invite"),
    path("google/login/", views.google_login, name="google_login"),
    path("google/register/", views.google_register, name="google_register"),
    path("google/auth/", views.google_authorize, name="google_authorize"),
]

loog/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"


urlpatterns = [
    path("history/", views.ChatSessionList.as_view(), name="history"),
    path("<str:room_name>/", views.ChatSessionView.as_view(), name="session"),
    path("<str:room_name>/tag/", views.session_post_tag, name="session-tag"),
    path("join/<str:room_name>/", views.join_chat_session, name="join-session")
]

loog/discovery/urls.py
from django.urls import path
from . import views

app_name = "discovery"

urlpatterns = [
    path("", views.IndexPage.as_view(), name="discovery_index"),
]

loog/loog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),
    path("api/notifications/", include("notifications.api.routers")),
    path("discovery/", include("discovery.urls", namespace="discovery")),
    path("api/discovery/", include("discovery.api.routers")),
    path("chat/", include(("chat.urls", "chat"), namespace="chat")),
    path("api/chat/", include("chat.api.routers")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("api/accounts/", include("accounts.api.routers")),
    path("", include("main.urls", namespace="main")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loog/discovery/models.py
import logging

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import DateTimeModel

User = get_user_model()
logger = logging.getLogger(__name__)


class Tag(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=32)
    _type = models.IntegerField(verbose_name=_("Value"), default=-1)

    def __str__(self):
        return self.name


class TagAssignment(DateTimeModel):
    tag = models.ForeignKey(to=Tag, on_delete=models.PROTECT, verbose_name=_("Tag"))
    giver = models.ForeignKey(
        to=User, on_delete=models.PROTECT, related_name="receiver", verbose_name=_("Giver")
    )
    receiver = models.ForeignKey(to=User, on_delete=models.PROTECT, verbose_name=_("Receiver"))

    def __str__(self):
        return f"{self.giver} --> {self.receiver}: {self.tag}"

loog/discovery/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class TagForm(forms.Form):
    tag_limit = 5

    comma_separated_tags = forms.CharField(
        max_length=1024,
        help_text=_("Separate tags by comma, or pressing the enter key."),
        widget=forms.TextInput(attrs={'data-role': 'tagsinput'})
    )

    def clean_comma_separated_tags(self):
        comma_separated_tags = self.cleaned_data.get("comma_separated_tags", "").split(",")

        if len(comma_separated_tags) < self.tag_limit:
            raise ValidationError(_(f'At least {self.tag_limit} tags required.'), code='invalid')

        initial_tags = ','.join([tag.strip() for tag in comma_separated_tags])
        return initial_tags

loog/discovery/api/views.py
import uuid

from rest_framework import mixins, viewsets, permissions, generics, status
from rest_framework.response import Response

from accounts.api.serializers import UserSerializer
from accounts.models import User
from chat.models import ChatSession, ChatSessionUser
from discovery.models import Tag, TagAssignment
from discovery.utils import find_users, send_notifications
from .serializers import TagSerializer, TagAssignmentSerializer


class TagViewSet(mixins.ListModelMixin,
                 mixins.CreateModelMixin,
                 mixins.RetrieveModelMixin,
                 viewsets.GenericViewSet):
    """CR API of Tag for authenticated users"""
    queryset = Tag.objects.all()
    serializer_class = TagSerializer


class TagAssignmentViewSet(viewsets.ModelViewSet):
    """CRUD API of TagAssignment for admin users"""
    serializer_class = TagAssignmentSerializer
    permission_classes = (permissions.IsAdminUser,)
    queryset = TagAssignment.objects.all()


class UserTagAssignmentViewSet(mixins.ListModelMixin,
                               mixins.CreateModelMixin,
                               mixins.RetrieveModelMixin,
                               viewsets.GenericViewSet):
    """CR API of TagAssignment for authenticated users"""
    queryset = TagAssignment.objects.all()
    serializer_class = TagAssignmentSerializer


class SearchUserAPI(generics.ListAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = UserSerializer

    def get_queryset(self):
        user = self.request.user
        query = self.request.query_params.get('query', '').strip()

        if query == '':
            return Response(
                data={
                    "error": "Required query parameter: query."
                },
                status=status.HTTP_400_BAD_REQUEST
            )

        session_obj = ChatSession.objects.create(
            query=query,
            room_name=uuid.uuid4().hex[:10].upper()
        )
        ChatSessionUser.objects.create(
            user=user,
            session=session_obj
        )
        user_score = find_users(query)
        if self.request.user.id in user_score:
            user_score.pop(self.request.user.id)
        payload = {
            'title': 'NEW LOOG',
            'body': f'User: {user}, Query: {query}',
            'url': session_obj.get_absolute_url(),
            'icon_url': self.request.user.profile.get_avatar()
        }
        send_notifications(user_score.keys(), payload)
        return User.objects.filter(id__in=user_score.keys())

loog/discovery/views.py
from django.views import generic

from core.mixins import ProfileRequiredMixin


class IndexPage(ProfileRequiredMixin, generic.TemplateView):
    template_name = 'discovery/index.html'

loog/templates/discovery/index.html
{% extends 'base.html' %}

{% block title %}
    Discovery
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Welcome to the discovery!</h1>
        <p>This is the index page of the discovery!</p>
    </div>
{% endblock %}

loog/templates/discovery/profile.html
{% extends "base.html" %}

{% block content %}


<div class="container">
    <div class="row">
        <a href="{% url 'discovery:invite' %}">Invite your friends!</a>
        {% for key, value in tags.items reversed %}
        <div class="col-sm">
            <p class="text-uppercase mt-3 text-center">{{ key }}</p>
            <ul class="list-group">
                {% for tag, count in value.items %}
                <a href="#" class="list-group-item d-flex justify-content-between align-items-center">{{tag}}

                    {% if count >= 5 %}
                    <span class="badge badge-danger badge-pill">{{count}}</span>
                    {% elif count >= 2 %}
                    <span class="badge badge-warning badge-pill">{{count}}</span>
                    {% else %}
                    <span class="badge badge-primary badge-pill">{{count}}</span>
                    {% endif %}

                </a>
                {% endfor %}
            </ul>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

loog/templates/discovery/profile_complete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Profile {% endblock %}

{% block content %}
    <div class="container py-5">
        <h1>Profile</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>

    </div>

{% endblock %}

loog/templates/discovery/profile_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Profile {% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        {% if has_tag_form %}
            <h1>Inviter's tags</h1>
            <p>You have been invited by @{{ inviter }}, enter 5 tags that introduce him/her:</p>

            <form action="{% url 'discovery:profile_set_tag' %}" method="POST">
                {% csrf_token %}
                {{ tag_form | crispy }}
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
            <hr>
        {% endif %}
        <h1>Profile</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>

    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'js/tagsinput.js' %}"></script>
{% endblock %}